
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label l_rectangle;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Label l_x1;
	
	private global::Gtk.SpinButton spinbutton7;
	
	private global::Gtk.HBox hbox5;
	
	private global::Gtk.Label l_x2;
	
	private global::Gtk.SpinButton spinbutton8;
	
	private global::Gtk.HBox hbox6;
	
	private global::Gtk.Label l_x3;
	
	private global::Gtk.SpinButton spinbutton9;
	
	private global::Gtk.HBox hbox7;
	
	private global::Gtk.Label l_x4;
	
	private global::Gtk.SpinButton spinbutton10;
	
	private global::Gtk.HBox hbox8;
	
	private global::Gtk.Label l_x5;
	
	private global::Gtk.HBox hbox9;
	
	private global::Gtk.Label l_x6;
	
	private global::Gtk.HBox hbox10;
	
	private global::Gtk.Label l_x7;
	
	private global::Gtk.HBox hbox11;
	
	private global::Gtk.Button button3;
	
	private global::Gtk.HBox hbox12;
	
	private global::Gtk.Button button4;
	
	private global::Gtk.DrawingArea drawingarea2;
	
	private global::Gtk.Image image;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 600;
		this.HeightRequest = 450;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Point in Rectangle");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 600;
		this.DefaultHeight = 400;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.WidthRequest = 600;
		this.hbox1.HeightRequest = 450;
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.WidthRequest = 150;
		this.vbox2.HeightRequest = 450;
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.HeightRequest = 0;
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.l_rectangle = new global::Gtk.Label ();
		this.l_rectangle.HeightRequest = 30;
		this.l_rectangle.Name = "l_rectangle";
		this.l_rectangle.LabelProp = global::Mono.Unix.Catalog.GetString ("Rectangle:");
		this.l_rectangle.UseMarkup = true;
		this.hbox3.Add (this.l_rectangle);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.l_rectangle]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.l_x1 = new global::Gtk.Label ();
		this.l_x1.HeightRequest = 30;
		this.l_x1.Name = "l_x1";
		this.l_x1.LabelProp = global::Mono.Unix.Catalog.GetString ("x1");
		this.l_x1.UseMarkup = true;
		this.hbox4.Add (this.l_x1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.l_x1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		w3.Padding = ((uint)(5));
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinbutton7 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton7.CanFocus = true;
		this.spinbutton7.Name = "spinbutton7";
		this.spinbutton7.Adjustment.PageIncrement = 10;
		this.spinbutton7.ClimbRate = 1;
		this.spinbutton7.Numeric = true;
		this.hbox4.Add (this.spinbutton7);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.spinbutton7]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.l_x2 = new global::Gtk.Label ();
		this.l_x2.HeightRequest = 30;
		this.l_x2.Name = "l_x2";
		this.l_x2.LabelProp = global::Mono.Unix.Catalog.GetString ("y1");
		this.l_x2.UseMarkup = true;
		this.hbox5.Add (this.l_x2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.l_x2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.spinbutton8 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton8.CanFocus = true;
		this.spinbutton8.Name = "spinbutton8";
		this.spinbutton8.Adjustment.PageIncrement = 10;
		this.spinbutton8.ClimbRate = 1;
		this.spinbutton8.Numeric = true;
		this.hbox5.Add (this.spinbutton8);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.spinbutton8]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add (this.hbox5);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.l_x3 = new global::Gtk.Label ();
		this.l_x3.HeightRequest = 30;
		this.l_x3.Name = "l_x3";
		this.l_x3.LabelProp = global::Mono.Unix.Catalog.GetString ("x2");
		this.l_x3.UseMarkup = true;
		this.hbox6.Add (this.l_x3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.l_x3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.spinbutton9 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton9.CanFocus = true;
		this.spinbutton9.Name = "spinbutton9";
		this.spinbutton9.Adjustment.PageIncrement = 10;
		this.spinbutton9.ClimbRate = 1;
		this.spinbutton9.Numeric = true;
		this.hbox6.Add (this.spinbutton9);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.spinbutton9]));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox2.Add (this.hbox6);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
		w11.Position = 3;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.l_x4 = new global::Gtk.Label ();
		this.l_x4.HeightRequest = 30;
		this.l_x4.Name = "l_x4";
		this.l_x4.LabelProp = global::Mono.Unix.Catalog.GetString ("y2");
		this.l_x4.UseMarkup = true;
		this.hbox7.Add (this.l_x4);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.l_x4]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.spinbutton10 = new global::Gtk.SpinButton (0, 100, 1);
		this.spinbutton10.CanFocus = true;
		this.spinbutton10.Name = "spinbutton10";
		this.spinbutton10.Adjustment.PageIncrement = 10;
		this.spinbutton10.ClimbRate = 1;
		this.spinbutton10.Numeric = true;
		this.hbox7.Add (this.spinbutton10);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.spinbutton10]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox2.Add (this.hbox7);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
		w14.Position = 4;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.l_x5 = new global::Gtk.Label ();
		this.l_x5.HeightRequest = 30;
		this.l_x5.Name = "l_x5";
		this.l_x5.LabelProp = global::Mono.Unix.Catalog.GetString ("Point:");
		this.l_x5.UseMarkup = true;
		this.hbox8.Add (this.l_x5);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.l_x5]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		this.vbox2.Add (this.hbox8);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
		w16.Position = 5;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.l_x6 = new global::Gtk.Label ();
		this.l_x6.HeightRequest = 30;
		this.l_x6.Name = "l_x6";
		this.l_x6.LabelProp = global::Mono.Unix.Catalog.GetString ("x1");
		this.l_x6.UseMarkup = true;
		this.hbox9.Add (this.l_x6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.l_x6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox2.Add (this.hbox9);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox9]));
		w18.Position = 6;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.l_x7 = new global::Gtk.Label ();
		this.l_x7.HeightRequest = 30;
		this.l_x7.Name = "l_x7";
		this.l_x7.LabelProp = global::Mono.Unix.Catalog.GetString ("x1");
		this.l_x7.UseMarkup = true;
		this.hbox10.Add (this.l_x7);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.l_x7]));
		w19.Position = 0;
		w19.Expand = false;
		w19.Fill = false;
		this.vbox2.Add (this.hbox10);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox10]));
		w20.Position = 7;
		w20.Expand = false;
		w20.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox11 = new global::Gtk.HBox ();
		this.hbox11.Name = "hbox11";
		this.hbox11.Spacing = 6;
		// Container child hbox11.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button ();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox11.Add (this.button3);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.button3]));
		w21.Position = 0;
		w21.Expand = false;
		w21.Fill = false;
		this.vbox2.Add (this.hbox11);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox11]));
		w22.Position = 8;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox12 = new global::Gtk.HBox ();
		this.hbox12.Name = "hbox12";
		this.hbox12.Spacing = 6;
		// Container child hbox12.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button ();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.hbox12.Add (this.button4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.button4]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox2.Add (this.hbox12);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox12]));
		w24.Position = 9;
		w24.Expand = false;
		w24.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w25.Position = 0;
		w25.Expand = false;
		w25.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.drawingarea2 = new global::Gtk.DrawingArea ();
		this.drawingarea2.Name = "drawingarea2";
		this.hbox1.Add (this.drawingarea2);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.drawingarea2]));
		w26.Position = 1;
		w26.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image = new global::Gtk.Image ();
		this.image.Name = "image";
		this.image.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "../../../Pictures/abstract.jpeg"));
		this.hbox1.Add (this.image);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image]));
		w27.Position = 2;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
