
// This file has been generated by the GUI designer. Do not modify.

public partial class FormTurtleGraphics
{
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Button buttonDraw;
	
	private global::Gtk.Button buttonReset;
	
	private global::Gtk.Button buttonShowHideTurtle;
	
	private global::Gtk.DrawingArea da;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget FormTurtleGraphics
		this.Name = "FormTurtleGraphics";
		this.Title = global::Mono.Unix.Catalog.GetString ("Turtle Graphics - Example");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child FormTurtleGraphics.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonDraw = new global::Gtk.Button ();
		this.buttonDraw.WidthRequest = 150;
		this.buttonDraw.HeightRequest = 50;
		this.buttonDraw.CanFocus = true;
		this.buttonDraw.Name = "buttonDraw";
		this.buttonDraw.UseUnderline = true;
		this.buttonDraw.Label = global::Mono.Unix.Catalog.GetString ("Draw");
		this.vbox1.Add (this.buttonDraw);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonDraw]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonReset = new global::Gtk.Button ();
		this.buttonReset.WidthRequest = 150;
		this.buttonReset.HeightRequest = 50;
		this.buttonReset.CanFocus = true;
		this.buttonReset.Name = "buttonReset";
		this.buttonReset.UseUnderline = true;
		this.buttonReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.vbox1.Add (this.buttonReset);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonReset]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.buttonShowHideTurtle = new global::Gtk.Button ();
		this.buttonShowHideTurtle.WidthRequest = 150;
		this.buttonShowHideTurtle.HeightRequest = 50;
		this.buttonShowHideTurtle.CanFocus = true;
		this.buttonShowHideTurtle.Name = "buttonShowHideTurtle";
		this.buttonShowHideTurtle.UseUnderline = true;
		this.buttonShowHideTurtle.Label = global::Mono.Unix.Catalog.GetString ("Hide Turtle");
		this.vbox1.Add (this.buttonShowHideTurtle);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttonShowHideTurtle]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.hbox1.Add (this.vbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.da = new global::Gtk.DrawingArea ();
		this.da.Name = "da";
		this.hbox1.Add (this.da);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.da]));
		w5.Position = 1;
		w5.Padding = ((uint)(10));
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1946;
		this.DefaultHeight = 1248;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
